### ISSUE TITLE
by a semantic version constraint matched against a Composer dependency not working

### ISSUE THREAD

**Issue by DanielSiepmann** [staabm/phpstan-todo-by#52]
The "by a semantic version constraint matched against a Composer dependency" approach does not work. We receive the following output:

```
 ------ ---------------------------------------------------------
  Line   packages/site_codappix/ext_localconf.php
 ------ ---------------------------------------------------------
  10     Package "typo3/cms-core" is not installed via Composer.
 ------ ---------------------------------------------------------
```

I tried to debug via xdebug and it looks like the `!InstalledVersions::isInstalled` call is heading to phpstan phar version and its own packages composer dependencies instead of the actual project dependencies.

**Comment by staabm** [comment]
thanks for reporting. it works in my tests as expected.

could you create a small reproducing repo? It might be something specific to typo3

**Comment by DanielSiepmann** [comment]
Thanks for your fast response, and sure: https://github.com/DanielSiepmann/phpstan-todo-by-issue-52

I broke our setup down to the minimum. It seems the issue is caused by typo3/minimal dependency.
Removing that dependency removes the issue.

So not really related to TYPO3 I guess, but to metapackages in general? I'm not too deep into this topic.

**Comment by staabm** [comment]
thanks for the repro. as soon as `typo3/minimal` is removed from the repro it starts to work. it seems one of the dependencies is fiddling with autoloading

**Comment by DanielSiepmann** [comment]
I could further reduce to only include typo3/cms-core and typo3/cms-backend.

**Comment by staabm** [comment]
I think it will be fixed with https://github.com/staabm/phpstan-todo-by/pull/54 - I need a proper automated test for staabm/phpstan-todo-by to land it though.

could you work on thatß

**Comment by staabm** [comment]
fix released in https://github.com/staabm/phpstan-todo-by/releases/tag/0.1.17

**Comment by DanielSiepmann** [comment]
Thank you very much for such a fast fix.
I'll give it a try tomorrow and only respond if we still have issues :)
